defmodule KnraWeb.ReportComponents do
  @moduledoc """
  Shared pieces of the Reporting pages: filter bar, printable report header,
  and two single-series charts (horizontal bar list and daily columns). Charts
  use one hue (the dark KNRA blue) since each shows a single measure; exact
  values sit beside each bar and in the tables, and every bar has a tooltip.
  """
  use Phoenix.Component
  use KnraWeb, :verified_routes

  import KnraWeb.CoreComponents, only: [icon: 1]
  import KnraWeb.UI, only: [btn: 2]

  attr :filters, :map, required: true
  attr :lanes, :list, required: true
  attr :export, :string, required: true, doc: "report key for the CSV export path"

  def report_filters(assigns) do
    today = Knra.Time.today()

    assigns =
      assign(assigns,
        today: today,
        quick: [
          {"Last 7 days", Date.add(today, -6), today},
          {"Last 30 days", Date.add(today, -29), today},
          {"This month", Date.beginning_of_month(today), today},
          {"Last month", Date.beginning_of_month(Date.add(Date.beginning_of_month(today), -1)),
           Date.add(Date.beginning_of_month(today), -1)}
        ]
      )

    ~H"""
    <div class="noprint mb-5 rounded-md border border-line bg-white px-5 py-4">
      <form id="report-filters" phx-change="filter" class="flex flex-wrap items-end gap-3">
        <label class="text-xs font-semibold text-muted">
          From
          <input
            type="date"
            name="from"
            value={Date.to_iso8601(@filters.from)}
            max={Date.to_iso8601(@today)}
            class="input input-sm mt-1 block"
          />
        </label>
        <label class="text-xs font-semibold text-muted">
          To
          <input
            type="date"
            name="to"
            value={Date.to_iso8601(@filters.to)}
            max={Date.to_iso8601(@today)}
            class="input input-sm mt-1 block"
          />
        </label>
        <label class="text-xs font-semibold text-muted">
          Lane
          <select name="lane_id" class="select select-sm mt-1 block">
            <option value="">All lanes</option>
            <option :for={l <- @lanes} value={l.id} selected={@filters.lane_id == l.id}>
              {l.name} · {l.device_code}
            </option>
          </select>
        </label>
        <div class="flex flex-wrap gap-1.5">
          <button
            :for={{label, from, to} <- @quick}
            type="button"
            phx-click="range"
            phx-value-from={Date.to_iso8601(from)}
            phx-value-to={Date.to_iso8601(to)}
            class={[
              btn(:secondary, :sm),
              (@filters.from == from and @filters.to == to) && "border-brand text-brand"
            ]}
          >
            {label}
          </button>
        </div>
        <div class="flex-1"></div>
        <a
          href={~p"/reporting/#{@export}/export?#{Knra.Reporting.to_params(@filters)}"}
          class={btn(:secondary, :sm)}
        >
          <.icon name="hero-arrow-down-tray" class="size-4" /> CSV
        </a>
        <button type="button" data-print class={btn(:primary, :sm)}>
          <.icon name="hero-printer" class="size-4" /> Print / PDF
        </button>
      </form>
    </div>
    """
  end

  attr :title, :string, required: true
  attr :filters, :map, required: true
  attr :lane_name, :string, default: nil
  attr :generated_by, :string, required: true

  def report_header(assigns) do
    ~H"""
    <header class="mb-6 border-b-2 border-brand pb-4">
      <div class="flex flex-wrap items-center gap-4">
        <img
          src={~p"/images/knra-logo.jpeg"}
          alt="Kenya Nuclear Regulatory Authority"
          class="hidden h-12 print:block"
        />
        <div class="min-w-0 flex-1">
          <h1 class="text-2xl font-bold tracking-tight">{@title}</h1>
          <p class="mt-1 text-sm text-muted">
            Reporting {Knra.Time.format_date(@filters.from)} – {Knra.Time.format_date(@filters.to)} · {@lane_name ||
              "All lanes"} · Port of Mombasa
          </p>
        </div>
        <div class="text-right text-xs text-muted">
          <div>Report date {Knra.Time.format(Knra.Time.now())}</div>
          <div>Generated by {@generated_by}</div>
        </div>
      </div>
    </header>
    """
  end

  attr :title, :string, required: true
  attr :id, :string, required: true
  attr :class, :any, default: nil
  slot :inner_block, required: true
  slot :note

  def report_section(assigns) do
    ~H"""
    <section
      id={@id}
      class={["mb-6 break-inside-avoid rounded-md border border-line bg-white", @class]}
    >
      <h2 class="border-b border-line-soft bg-panel px-5 py-3 text-[15px] font-bold">{@title}</h2>
      <div class="px-5 py-4">{render_slot(@inner_block)}</div>
      <p :if={@note != []} class="border-t border-line-soft px-5 py-2.5 text-xs text-muted">
        {render_slot(@note)}
      </p>
    </section>
    """
  end

  @doc "Horizontal bars for labelled counts, sorted as given. One hue; value shown beside each bar."
  attr :rows, :list, required: true, doc: "[{label, count}]"
  attr :unit, :string, default: ""
  attr :empty, :string, default: "Nothing in this period."

  def bar_list(assigns) do
    max = assigns.rows |> Enum.map(&elem(&1, 1)) |> Enum.max(fn -> 0 end)
    total = assigns.rows |> Enum.map(&elem(&1, 1)) |> Enum.sum()
    assigns = assign(assigns, max: max, total: total)

    ~H"""
    <div :if={@total == 0} class="text-[13px] text-subtle">{@empty}</div>
    <ul :if={@total > 0} class="space-y-2 [print-color-adjust:exact]">
      <li
        :for={{label, n} <- @rows}
        class="grid grid-cols-[minmax(0,14rem)_1fr_3.5rem] items-center gap-3 text-[13px]"
      >
        <span class="truncate text-ink" title={label}>{label}</span>
        <span class="h-3.5 rounded-sm bg-canvas">
          <span
            class="block h-3.5 rounded-r-[4px] bg-brand-dark"
            style={"width: #{if @max > 0, do: max(n * 100 / @max, if(n > 0, do: 1.5, else: 0)), else: 0}%"}
            title={"#{label}: #{n}#{@unit} (#{pct(n, @total)})"}
          >
          </span>
        </span>
        <span class="text-right tabular-nums text-muted">{n}</span>
      </li>
    </ul>
    """
  end

  @doc "Daily columns for one measure (e.g. containers screened). Single axis from zero."
  attr :days, :list, required: true, doc: "[%{date, value, detail}]"
  attr :label, :string, required: true

  def daily_columns(assigns) do
    max = assigns.days |> Enum.map(& &1.value) |> Enum.max(fn -> 0 end)
    n = length(assigns.days)
    # label every k-th day so labels never collide
    every = max(1, div(n + 13, 14))
    assigns = assign(assigns, max: max, top: nice_max(max), every: every)

    ~H"""
    <div class="[print-color-adjust:exact]" role="img" aria-label={"#{@label} per day"}>
      <div class="flex gap-2">
        <div
          class="flex w-8 flex-col justify-between text-right text-[11px] tabular-nums text-subtle"
          style="height: 10rem"
        >
          <span>{@top}</span>
          <span>{div(@top, 2)}</span>
          <span>0</span>
        </div>
        <div class="relative flex-1">
          <div
            class="pointer-events-none absolute inset-0 flex flex-col justify-between"
            style="height: 10rem"
          >
            <span class="border-t border-line-soft"></span>
            <span class="border-t border-line-soft"></span>
            <span class="border-t border-line"></span>
          </div>
          <div class="relative flex items-end gap-[2px]" style="height: 10rem">
            <div
              :for={d <- @days}
              class="group flex h-full flex-1 items-end"
              title={"#{Knra.Time.format_date(d.date)}: #{d.value} #{String.downcase(@label)}#{d[:detail] && " · " <> d.detail}"}
            >
              <span
                class="block w-full rounded-t-[4px] bg-brand-dark group-hover:bg-brand"
                style={"height: #{if @top > 0, do: d.value * 100 / @top, else: 0}%"}
              >
              </span>
            </div>
          </div>
          <div class="mt-1 flex gap-[2px] text-[10px] text-subtle">
            <span
              :for={{d, i} <- Enum.with_index(@days)}
              class="flex-1 overflow-visible whitespace-nowrap text-center"
            >
              {if rem(i, @every) == 0, do: Calendar.strftime(d.date, "%d %b")}
            </span>
          </div>
        </div>
      </div>
    </div>
    """
  end

  @doc "A row of headline figures."
  attr :items, :list, required: true, doc: "[{label, value, sub}]"

  def figures(assigns) do
    ~H"""
    <div class="mb-6 grid grid-cols-2 gap-3 md:grid-cols-4">
      <div
        :for={{label, value, sub} <- @items}
        class="break-inside-avoid rounded-md border border-line bg-white px-4 py-3"
      >
        <div class="text-[11px] font-bold uppercase tracking-[0.06em] text-subtle">{label}</div>
        <div class="mt-0.5 text-2xl font-bold tabular-nums">{value}</div>
        <div :if={sub} class="text-xs text-muted">{sub}</div>
      </div>
    </div>
    """
  end

  def pct(_n, 0), do: "0%"
  def pct(n, total), do: "#{Float.round(n * 100 / total, 1)}%"

  @doc "Minutes as `45 min`, `3.2 h` or `2.1 d`."
  def duration(nil), do: "—"
  def duration(min) when min < 90, do: "#{round(min)} min"
  def duration(min) when min < 2880, do: "#{Float.round(min / 60, 1)} h"
  def duration(min), do: "#{Float.round(min / 1440, 1)} d"

  defp nice_max(0), do: 2

  defp nice_max(max) do
    magnitude = :math.pow(10, floor(:math.log10(max)))

    step =
      Enum.find([1, 2, 2.5, 5, 10], fn s -> max <= s * magnitude end) * magnitude

    step = round(step)
    if rem(step, 2) == 0, do: step, else: step + 1
  end
end
